language: php

php:
  - "7.4"

services:
  - mysql

install:
  - composer install --no-interaction
  - ./bin/console doctrine:database:create --env=travis
  - ./bin/console doctrine:migration:migrate --env=travis --no-interaction

script:
  - ./vendor/bin/simple-phpunit